services:
  elegans:
    container_name: elegans
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
